import { cn } from '@/lib/utils'
import type { FC, CSSProperties, MouseEventHandler, SVGProps } from 'react'

import {
  AcademicCapIcon, AdjustmentsHorizontalIcon, ArrowDownIcon, ArrowDownTrayIcon,
  ArrowLeftIcon, ArrowPathIcon, ArrowPathRoundedSquareIcon, ArrowRightIcon,
  ArrowRightOnRectangleIcon, ArrowTopRightOnSquareIcon, ArrowTrendingUpIcon,
  Bars3Icon, BellIcon, BellSlashIcon, BoltIcon, BookmarkIcon, BriefcaseIcon,
  BuildingOfficeIcon, CalendarIcon, CameraIcon, ChartBarIcon, ChartBarSquareIcon,
  ChatBubbleLeftEllipsisIcon, ChatBubbleLeftRightIcon, CheckBadgeIcon, CheckCircleIcon,
  CheckIcon, ChevronDownIcon, ChevronLeftIcon, ChevronRightIcon,
  ClipboardDocumentListIcon, ClockIcon, CloudArrowDownIcon, CpuChipIcon,
  CreditCardIcon, DocumentDuplicateIcon, DocumentIcon, DocumentTextIcon,
  EllipsisHorizontalCircleIcon, EllipsisHorizontalIcon, EnvelopeIcon, EnvelopeOpenIcon,
  ExclamationCircleIcon, ExclamationTriangleIcon, EyeIcon, EyeSlashIcon,
  FireIcon, FlagIcon, FolderOpenIcon, FunnelIcon, GlobeAltIcon, HeartIcon,
  HomeModernIcon, IdentificationIcon, InboxArrowDownIcon, InformationCircleIcon, KeyIcon, LanguageIcon,
  LightBulbIcon, LinkIcon, LinkSlashIcon, ListBulletIcon, LockClosedIcon, LockOpenIcon,
  MagnifyingGlassIcon, MagnifyingGlassMinusIcon, MagnifyingGlassPlusIcon, MapPinIcon,
  MicrophoneIcon, MinusIcon, NewspaperIcon, NoSymbolIcon, PaperAirplaneIcon,
  PaperClipIcon, PencilIcon, PencilSquareIcon, PhoneXMarkIcon, PhotoIcon, PlusIcon,
  PresentationChartLineIcon, RectangleStackIcon, ShareIcon, ShieldCheckIcon, SparklesIcon,
  Squares2X2Icon, StarIcon, StopCircleIcon, TagIcon, TrashIcon, TrophyIcon,
  UserCircleIcon, UserIcon, UserMinusIcon, UserPlusIcon, UsersIcon,
  VideoCameraIcon, VideoCameraSlashIcon, ViewColumnsIcon, XCircleIcon, XMarkIcon,
  PlusCircleIcon, PhoneIcon, MegaphoneIcon, ClipboardDocumentCheckIcon, CodeBracketIcon,
  CalendarDaysIcon, InboxIcon, BookOpenIcon, QuestionMarkCircleIcon, HandThumbUpIcon,
  RocketLaunchIcon, Cog6ToothIcon, ViewfinderCircleIcon, ArrowUturnLeftIcon,
} from '@heroicons/react/24/outline'

import {
  AcademicCapIcon as AcademicCapSolid, AdjustmentsHorizontalIcon as AdjustmentsHorizontalSolid,
  ArrowDownIcon as ArrowDownSolid, ArrowDownTrayIcon as ArrowDownTraySolid,
  ArrowLeftIcon as ArrowLeftSolid, ArrowPathIcon as ArrowPathSolid,
  ArrowPathRoundedSquareIcon as ArrowPathRoundedSquareSolid, ArrowRightIcon as ArrowRightSolid,
  ArrowRightOnRectangleIcon as ArrowRightOnRectangleSolid,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareSolid,
  ArrowTrendingUpIcon as ArrowTrendingUpSolid, Bars3Icon as Bars3Solid,
  BellIcon as BellSolid, BellSlashIcon as BellSlashSolid, BoltIcon as BoltSolid,
  BookmarkIcon as BookmarkSolid, BriefcaseIcon as BriefcaseSolid,
  BuildingOfficeIcon as BuildingOfficeSolid, CalendarIcon as CalendarSolid,
  CameraIcon as CameraSolid, ChartBarIcon as ChartBarSolid,
  ChartBarSquareIcon as ChartBarSquareSolid,
  ChatBubbleLeftEllipsisIcon as ChatBubbleLeftEllipsisSolid,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightSolid,
  CheckBadgeIcon as CheckBadgeSolid, CheckCircleIcon as CheckCircleSolid,
  CheckIcon as CheckSolid, ChevronDownIcon as ChevronDownSolid,
  ChevronLeftIcon as ChevronLeftSolid, ChevronRightIcon as ChevronRightSolid,
  ClipboardDocumentListIcon as ClipboardDocumentListSolid, ClockIcon as ClockSolid,
  CloudArrowDownIcon as CloudArrowDownSolid, CpuChipIcon as CpuChipSolid,
  CreditCardIcon as CreditCardSolid, DocumentDuplicateIcon as DocumentDuplicateSolid,
  DocumentIcon as DocumentSolid, DocumentTextIcon as DocumentTextSolid,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircleSolid,
  EllipsisHorizontalIcon as EllipsisHorizontalSolid,
  EnvelopeIcon as EnvelopeSolid, EnvelopeOpenIcon as EnvelopeOpenSolid,
  ExclamationCircleIcon as ExclamationCircleSolid,
  ExclamationTriangleIcon as ExclamationTriangleSolid,
  EyeIcon as EyeSolid, EyeSlashIcon as EyeSlashSolid, FireIcon as FireSolid,
  FlagIcon as FlagSolid, FolderOpenIcon as FolderOpenSolid, FunnelIcon as FunnelSolid,
  GlobeAltIcon as GlobeAltSolid, HeartIcon as HeartSolid,
  HomeModernIcon as HomeModernSolid, InboxArrowDownIcon as InboxArrowDownSolid,
  IdentificationIcon as IdentificationSolid,
  InformationCircleIcon as InformationCircleSolid, KeyIcon as KeySolid,
  LanguageIcon as LanguageSolid, LightBulbIcon as LightBulbSolid,
  LinkIcon as LinkSolid, LinkSlashIcon as LinkSlashSolid,
  ListBulletIcon as ListBulletSolid, LockClosedIcon as LockClosedSolid,
  LockOpenIcon as LockOpenSolid, MagnifyingGlassIcon as MagnifyingGlassSolid,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinusSolid,
  MagnifyingGlassPlusIcon as MagnifyingGlassPlusSolid, MapPinIcon as MapPinSolid,
  MicrophoneIcon as MicrophoneSolid, MinusIcon as MinusSolid,
  NewspaperIcon as NewspaperSolid, NoSymbolIcon as NoSymbolSolid,
  PaperAirplaneIcon as PaperAirplaneSolid, PaperClipIcon as PaperClipSolid,
  PencilIcon as PencilSolid, PencilSquareIcon as PencilSquareSolid,
  PhoneXMarkIcon as PhoneXMarkSolid, PhotoIcon as PhotoSolid, PlusIcon as PlusSolid,
  PresentationChartLineIcon as PresentationChartLineSolid,
  RectangleStackIcon as RectangleStackSolid, ShareIcon as ShareSolid,
  ShieldCheckIcon as ShieldCheckSolid,
  SparklesIcon as SparklesSolid, Squares2X2Icon as Squares2X2Solid,
  StarIcon as StarSolid, StopCircleIcon as StopCircleSolid, TagIcon as TagSolid,
  TrashIcon as TrashSolid, TrophyIcon as TrophySolid,
  UserCircleIcon as UserCircleSolid, UserIcon as UserSolid,
  UserMinusIcon as UserMinusSolid, UserPlusIcon as UserPlusSolid,
  UsersIcon as UsersSolid, VideoCameraIcon as VideoCameraSolid,
  VideoCameraSlashIcon as VideoCameraSlashSolid, ViewColumnsIcon as ViewColumnsSolid,
  XCircleIcon as XCircleSolid, XMarkIcon as XMarkSolid,
  PlusCircleIcon as PlusCircleSolid, PhoneIcon as PhoneSolid, MegaphoneIcon as MegaphoneSolid,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckSolid, CodeBracketIcon as CodeBracketSolid,
  CalendarDaysIcon as CalendarDaysSolid, InboxIcon as InboxSolid, BookOpenIcon as BookOpenSolid,
  QuestionMarkCircleIcon as QuestionMarkCircleSolid, HandThumbUpIcon as HandThumbUpSolid,
  RocketLaunchIcon as RocketLaunchSolid, Cog6ToothIcon as Cog6ToothSolid,
  ViewfinderCircleIcon as ViewfinderCircleSolid, ArrowUturnLeftIcon as ArrowUturnLeftSolid,
} from '@heroicons/react/24/solid'

type HeroIcon = FC<SVGProps<SVGSVGElement>>

const outlineMap: Record<string, HeroIcon> = {
  add_circle: PlusCircleIcon, bar_chart: ChartBarIcon, call: PhoneIcon, campaign: MegaphoneIcon,
  celebration: SparklesIcon, chat_bubble: ChatBubbleLeftEllipsisIcon, checklist: ClipboardDocumentCheckIcon,
  code: CodeBracketIcon, dashboard: Squares2X2Icon, edit_calendar: CalendarDaysIcon,
  emoji_events: TrophyIcon, event_available: CalendarDaysIcon, event_busy: XCircleIcon,
  fact_check: ClipboardDocumentCheckIcon, filter_alt: FunnelIcon, filter_list: FunnelIcon,
  group_add: UserPlusIcon, how_to_reg: CheckBadgeIcon, inbox: InboxIcon, leaderboard: ChartBarIcon,
  menu_book: BookOpenIcon, person_edit: PencilSquareIcon, psychology_alt: AcademicCapIcon,
  quiz: QuestionMarkCircleIcon, recommend: HandThumbUpIcon, record_voice_over: MicrophoneIcon,
  rocket_launch: RocketLaunchIcon, schedule: ClockIcon, settings: Cog6ToothIcon,
  target: ViewfinderCircleIcon, timer: ClockIcon, undo: ArrowUturnLeftIcon,
  video_library: VideoCameraIcon, work_history: BriefcaseIcon, work_off: BriefcaseIcon,
  account_circle: UserCircleIcon, add: PlusIcon, apartment: BuildingOfficeIcon,
  arrow_back: ArrowLeftIcon, arrow_downward: ArrowDownIcon, arrow_forward: ArrowRightIcon,
  assessment: ChartBarIcon, attach_file: PaperClipIcon, auto_awesome: SparklesIcon,
  badge: IdentificationIcon, bolt: BoltIcon, bookmark: BookmarkIcon, call_end: PhoneXMarkIcon,
  cancel: XCircleIcon, flash_on: BoltIcon, security: ShieldCheckIcon, shield: ShieldCheckIcon,
  chat: ChatBubbleLeftEllipsisIcon, check: CheckIcon, check_circle: CheckCircleIcon,
  chevron_left: ChevronLeftIcon, chevron_right: ChevronRightIcon, close: XMarkIcon,
  cloud_off: CloudArrowDownIcon, content_copy: DocumentDuplicateIcon,
  dashboard_customize: Squares2X2Icon, delete: TrashIcon, description: DocumentTextIcon,
  do_not_disturb_on: NoSymbolIcon, done_all: CheckIcon, download: ArrowDownTrayIcon,
  dynamic_feed: RectangleStackIcon, edit: PencilIcon, edit_note: PencilSquareIcon,
  edit_square: PencilSquareIcon, error: ExclamationCircleIcon, event: CalendarIcon,
  expand_more: ChevronDownIcon, favorite: HeartIcon, feed: NewspaperIcon, flag: FlagIcon,
  folder_open: FolderOpenIcon, forum: ChatBubbleLeftRightIcon,
  forward_to_inbox: InboxArrowDownIcon, group: UsersIcon, groups: UsersIcon,
  home_work: HomeModernIcon, hourglass_top: ClockIcon, image: PhotoIcon,
  info: InformationCircleIcon, insights: ChartBarSquareIcon, key_off: KeyIcon,
  label: TagIcon, lightbulb: LightBulbIcon, link: LinkIcon, link_off: LinkSlashIcon,
  local_fire_department: FireIcon, location_on: MapPinIcon, lock: LockClosedIcon,
  lock_open: LockOpenIcon, logout: ArrowRightOnRectangleIcon, magic_button: SparklesIcon,
  mail: EnvelopeIcon, mark_email_read: EnvelopeOpenIcon, mark_email_unread: EnvelopeIcon,
  menu: Bars3Icon, mic: MicrophoneIcon, mic_none: MicrophoneIcon, mic_off: MicrophoneIcon,
  military_tech: TrophyIcon, monitoring: PresentationChartLineIcon,
  more_horiz: EllipsisHorizontalIcon, notifications: BellIcon,
  notifications_off: BellSlashIcon, open_in_new: ArrowTopRightOnSquareIcon,
  payments: CreditCardIcon, person: UserIcon, person_add: UserPlusIcon,
  person_off: UserMinusIcon, person_remove: UserMinusIcon,
  person_search: MagnifyingGlassIcon, photo_camera: CameraIcon,
  picture_as_pdf: DocumentIcon, progress_activity: ArrowPathIcon,
  psychology: AcademicCapIcon, public: GlobeAltIcon,
  radio_button_unchecked: EllipsisHorizontalCircleIcon, refresh: ArrowPathIcon,
  remove: MinusIcon, repeat: ArrowPathRoundedSquareIcon, restart_alt: ArrowPathIcon,
  school: AcademicCapIcon, search: MagnifyingGlassIcon, send: PaperAirplaneIcon,
  share: ShareIcon, smart_toy: CpuChipIcon, sort: FunnelIcon, star: StarIcon,
  sticky_note_2: DocumentTextIcon, stop: StopCircleIcon,
  summarize: ClipboardDocumentListIcon, task_alt: CheckCircleIcon,
  translate: LanguageIcon, travel_explore: GlobeAltIcon, trending_up: ArrowTrendingUpIcon,
  tune: AdjustmentsHorizontalIcon, verified: CheckBadgeIcon, videocam: VideoCameraIcon,
  videocam_off: VideoCameraSlashIcon, view_kanban: ViewColumnsIcon,
  view_list: ListBulletIcon, visibility: EyeIcon, visibility_off: EyeSlashIcon,
  warning: ExclamationTriangleIcon, west: ArrowLeftIcon, work: BriefcaseIcon,
  workspace_premium: TrophyIcon, zoom_in: MagnifyingGlassPlusIcon,
  zoom_out: MagnifyingGlassMinusIcon,
}

const solidMap: Record<string, HeroIcon> = {
  add_circle: PlusCircleSolid, bar_chart: ChartBarSolid, call: PhoneSolid, campaign: MegaphoneSolid,
  celebration: SparklesSolid, chat_bubble: ChatBubbleLeftEllipsisSolid, checklist: ClipboardDocumentCheckSolid,
  code: CodeBracketSolid, dashboard: Squares2X2Solid, edit_calendar: CalendarDaysSolid,
  emoji_events: TrophySolid, event_available: CalendarDaysSolid, event_busy: XCircleSolid,
  fact_check: ClipboardDocumentCheckSolid, filter_alt: FunnelSolid, filter_list: FunnelSolid,
  group_add: UserPlusSolid, how_to_reg: CheckBadgeSolid, inbox: InboxSolid, leaderboard: ChartBarSolid,
  menu_book: BookOpenSolid, person_edit: PencilSquareSolid, psychology_alt: AcademicCapSolid,
  quiz: QuestionMarkCircleSolid, recommend: HandThumbUpSolid, record_voice_over: MicrophoneSolid,
  rocket_launch: RocketLaunchSolid, schedule: ClockSolid, settings: Cog6ToothSolid,
  target: ViewfinderCircleSolid, timer: ClockSolid, undo: ArrowUturnLeftSolid,
  video_library: VideoCameraSolid, work_history: BriefcaseSolid, work_off: BriefcaseSolid,
  account_circle: UserCircleSolid, add: PlusSolid, apartment: BuildingOfficeSolid,
  arrow_back: ArrowLeftSolid, arrow_downward: ArrowDownSolid, arrow_forward: ArrowRightSolid,
  assessment: ChartBarSolid, attach_file: PaperClipSolid, auto_awesome: SparklesSolid,
  badge: IdentificationSolid, bolt: BoltSolid, bookmark: BookmarkSolid, call_end: PhoneXMarkSolid,
  cancel: XCircleSolid, flash_on: BoltSolid, security: ShieldCheckSolid, shield: ShieldCheckSolid,
  chat: ChatBubbleLeftEllipsisSolid, check: CheckSolid, check_circle: CheckCircleSolid,
  chevron_left: ChevronLeftSolid, chevron_right: ChevronRightSolid, close: XMarkSolid,
  cloud_off: CloudArrowDownSolid, content_copy: DocumentDuplicateSolid,
  dashboard_customize: Squares2X2Solid, delete: TrashSolid, description: DocumentTextSolid,
  do_not_disturb_on: NoSymbolSolid, done_all: CheckSolid, download: ArrowDownTraySolid,
  dynamic_feed: RectangleStackSolid, edit: PencilSolid, edit_note: PencilSquareSolid,
  edit_square: PencilSquareSolid, error: ExclamationCircleSolid, event: CalendarSolid,
  expand_more: ChevronDownSolid, favorite: HeartSolid, feed: NewspaperSolid, flag: FlagSolid,
  folder_open: FolderOpenSolid, forum: ChatBubbleLeftRightSolid,
  forward_to_inbox: InboxArrowDownSolid, group: UsersSolid, groups: UsersSolid,
  home_work: HomeModernSolid, hourglass_top: ClockSolid, image: PhotoSolid,
  info: InformationCircleSolid, insights: ChartBarSquareSolid, key_off: KeySolid,
  label: TagSolid, lightbulb: LightBulbSolid, link: LinkSolid, link_off: LinkSlashSolid,
  local_fire_department: FireSolid, location_on: MapPinSolid, lock: LockClosedSolid,
  lock_open: LockOpenSolid, logout: ArrowRightOnRectangleSolid, magic_button: SparklesSolid,
  mail: EnvelopeSolid, mark_email_read: EnvelopeOpenSolid, mark_email_unread: EnvelopeSolid,
  menu: Bars3Solid, mic: MicrophoneSolid, mic_none: MicrophoneSolid, mic_off: MicrophoneSolid,
  military_tech: TrophySolid, monitoring: PresentationChartLineSolid,
  more_horiz: EllipsisHorizontalSolid, notifications: BellSolid,
  notifications_off: BellSlashSolid, open_in_new: ArrowTopRightOnSquareSolid,
  payments: CreditCardSolid, person: UserSolid, person_add: UserPlusSolid,
  person_off: UserMinusSolid, person_remove: UserMinusSolid,
  person_search: MagnifyingGlassSolid, photo_camera: CameraSolid,
  picture_as_pdf: DocumentSolid, progress_activity: ArrowPathSolid,
  psychology: AcademicCapSolid, public: GlobeAltSolid,
  radio_button_unchecked: EllipsisHorizontalCircleSolid, refresh: ArrowPathSolid,
  remove: MinusSolid, repeat: ArrowPathRoundedSquareSolid, restart_alt: ArrowPathSolid,
  school: AcademicCapSolid, search: MagnifyingGlassSolid, send: PaperAirplaneSolid,
  share: ShareSolid, smart_toy: CpuChipSolid, sort: FunnelSolid, star: StarSolid,
  sticky_note_2: DocumentTextSolid, stop: StopCircleSolid,
  summarize: ClipboardDocumentListSolid, task_alt: CheckCircleSolid,
  translate: LanguageSolid, travel_explore: GlobeAltSolid, trending_up: ArrowTrendingUpSolid,
  tune: AdjustmentsHorizontalSolid, verified: CheckBadgeSolid, videocam: VideoCameraSolid,
  videocam_off: VideoCameraSlashSolid, view_kanban: ViewColumnsSolid,
  view_list: ListBulletSolid, visibility: EyeSolid, visibility_off: EyeSlashSolid,
  warning: ExclamationTriangleSolid, west: ArrowLeftSolid, work: BriefcaseSolid,
  workspace_premium: TrophySolid, zoom_in: MagnifyingGlassPlusSolid,
  zoom_out: MagnifyingGlassMinusSolid,
}

interface IconProps {
  name: string
  className?: string
  solid?: boolean
  style?: CSSProperties
  onClick?: MouseEventHandler<HTMLSpanElement>
}

export function Icon({ name, className, solid = false, style, onClick }: IconProps) {
  const map = solid ? solidMap : outlineMap
  const IconComp = map[name?.trim()]
  if (!IconComp) return null
  return (
    <span className={cn('inline-flex', className)} style={style} onClick={onClick}>
      <IconComp className="w-[1em] h-[1em]" />
    </span>
  )
}
